application: nanoblok-editor
version: 1-0-1-alpha
runtime: python
api_version: 1

handlers:
- url: /(.*\.(js))
  static_files: static/\1
  upload: static/(.*\.(js))
  
<<<<<<< local
#- url: /favicon.ico
#  static_files: static/favicon.ico
#  upload: static/favicon.ico
#
- url: /
=======
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /*
>>>>>>> other
  script: main.py

<<<<<<< local
=======
- url: /save
  script: main.py
>>>>>>> other
